export const carPartsCheckedFrequently = [
  "Air conditioning system",
  "Air filter",
  "Alternator",
  "Ball joints",
  "Battery",
  "Belts (serpentine belt, timing belt)",
  "Brake fluid",
  "Brake pads",
  "Brake rotors",
  "Cabin air filter",
  "Catalytic converter",
  "CV joints",
  "Coolant",
  "Differential fluid",
  "Drive shaft",
  "Engine mounts",
  "Engine oil",
  "Exhaust system",
  "Fuses",
  "Fuel filter",
  "Fuel injectors",
  "Fuel pump",
  "Hoses",
  "Lights (headlights, taillights, turn signals)",
  "Oil filter",
  "Oxygen sensor",
  "PCV valve",
  "Power steering fluid",
  "Radiator",
  "Radiator cap",
  "Radiator fan",
  "Shock absorbers",
  "Spark plugs",
  "Starter motor",
  "Struts",
  "Thermostat",
  "Throttle body",
  "Tie rods",
  "Timing chain/belt",
  "Tire pressure",
  "Tire tread depth",
  "Tires",
  "Transmission fluid",
  "Transmission mounts",
  "U-joints",
  "Water pump",
  "Wheel alignment",
  "Wheel bearings",
  "Windshield wipers",
  "Wiper fluid",
];
